### ISSUE TITLE
Unable to load static jpeg image

### ISSUE THREAD

**Issue by kuehlc** [cornerstonejs/cornerstoneWebImageLoader#37]
I make an api call to append the headers for CORS, but the loadImage function fails. Tried loading this image: https://phpapi.rsna.org/image-viewer/v1/get/image?image-address=https://pubs.rsna.org/na101/home/literatum/publisher/rsna/journals/content/radiographics/2018/rg.2018.38.issue-1/rg.2018170120/20171226/images/large/rg.2018170120.fig1a.jpeg in our code, and on the example site: https://rawgit.com/cornerstonejs/cornerstoneWebImageLoader/master/examples/index.html, but it doesn't work even though it works in older version of the code in an example shown here: http://images.rsna.org/index.html?doi=10.1148/rg.2018170120&fig=fig1a

**Comment by dannyrb** [comment]
@kuehlc are you making sure the _server_ has the appropriate CORS headers set? Do you have a snippet/example?

**Comment by kuehlc** [comment]
@dannyrb The call is to the same code server side as the one that works with the same image in an older version of the project. The only difference that I can tell is the version of cornerstone. Are you asking for a snippet of the server side code, or which part do you want to see?

**Comment by kuehlc** [comment]
@dannyrb when I've looked at the dev tools for the return, the headers are the same for the one that works. They both allow for CORS. The blob for the one that doesn't work never finishes being created, so it doesn't show. It fails during cornerstone.loadImage call.

**Comment by kuehlc** [comment]
@dannyrb Were you able to see the example links from my first comment where it works in the old, but not the new, and how the same link that works in the old one doesn't work in the rawgit page? I don't want to rush you or anything. I get that this is an open source project. I just want to make sure what I posted was clear enough so you could see the issue.

**Comment by dannyrb** [comment]
@kuehlc, using the default JPEG image, I see these return headers:

![image](https://user-images.githubusercontent.com/5797588/73211957-33f77800-411b-11ea-8cb6-fb1b766ccc48.png)

Using your provided link, I see the following headers:

![image](https://user-images.githubusercontent.com/5797588/73212015-59848180-411b-11ea-8151-5ad3ef71d45a.png)

You can either match the response, or create a new loader that works with the response your API is using.

I do see where the application at the RSNA domain is successfully using the API endpoint in question, but because the source is minified, I'm not sure if they're doing any extra magic to decode the response.

It does look like both the web and wado image loaders are registered, and an older version of the libraries is being used. I don't believe any changes to the web image loader would have broken the the response parsing; to my knowledge, it's expected jpeg/png response for years.

**Comment by kuehlc** [comment]
So you're saying you believe that the working RSNA link is using JavaScript to manipulate the response? Thanks for the answer. I'll look more into these.

**Comment by kuehlc** [comment]
@dannyrb We found that they modified how they were handling the response as you mentioned. I'm going to modify the php. Does load image just expect the base64 string back directly, or what does it want? I'm looking at the code for the loadImage, but the answer is evading me for some reason for how the blob is created. Thanks in advance.

**Comment by kuehlc** [comment]
After this, I'll close the ticket.

**Comment by dannyrb** [comment]
Create Image is where the magic happens: https://github.com/cornerstonejs/cornerstoneWebImageLoader/blob/master/src/createImage.js#L57-L79

**Comment by kuehlc** [comment]
Okay, thank you.
